version: '3.9'

services:
  scholar-system:
    build: .
    container_name: scholar-system
    image: scholar-system:latest
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ${PWD}:/app
    ports:  
      - 3000:3000