version: '3.9'

networks:
  scholar-system-network:
    name: scholar-system-network
    driver: bridge

services:
  scholar-system:
    build: .
    container_name: scholar-system
    image: scholar-system:latest
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ${PWD}:/app
    ports:  
      - 3000:3000
    networks:
      - scholar-system-network

  postgres:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=4eEgT7pD87w6
      - TZ=America/Sao_Paulo
    ports:
      - 5432:5432
    networks:
      - scholar-system-network