name: ci-repository
run-name: Trigger CI Repository
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.12.1'
      - name: Install Modules
        run: npm ci
      - name: Run Tests
        run: npm run test